### ISSUE TITLE
\DI\get('AppName') cannot be found when not using redis.

### ISSUE THREAD

**Issue by Kambaa** [caoym/phpboot-example#1]
In the phpboot-example/config/config.php, i tried not using redis. Run the example project and see an exception about not finding AppName. Please update the documentation about this. 

Also, if you can write the docs in english that would be great ( google translate is not working good for me )

Thanks. 
Kambaa...

**Comment by caoym** [comment]
'AppName'  is legacy code, use 'App.name' instead

And I will try to write docs in english... thanks for the care and patience

**Comment by Kambaa** [comment]
Thank you very much...
