### ISSUE TITLE
NotFoundHttpException on requesting the first Book

### ISSUE THREAD

**Issue by Kambaa** [caoym/phpboot-example#2]
I cloned and tried to run the example. I edited the config file, added the book table and inserted the first row via phpMyAdmin, and when i tried to get the first row it gave me exception. 
My `http://example.com/public/books/1` request result is: 

```
{
    "error": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
    "message": ""
}
```

Log file says: 
```
[2017-11-20 16:31:45] log.WARNING: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message  {"0":"GET","1":"/public/books/1","@file":"/home/<MYUSERNAME>/PhpstormProjects/phpboot-example/vendor/caoym/phpboot/src/Application.php","@line":284} []
```

Could you enlighten me please. 
Thank you.

**Comment by Kambaa** [comment]
Found it!
Editing the uriPrefix to my public web dir solved the problem for me: (in Application.php file)
 `
 'App.uriPrefix' => '/public/',
`

**Comment by leejinzhu** [comment]
I have the same situation with you, but I don't know which `Application.Php` I should edit for solve the issue. Maybe u mean to edit the `/vendor/caoym/phpboot/Application.php`, I saw this. But in my opinion, I think this just default config if not supply config.php with framework function `createByDefault`,  I supplied another config file for sure. So I guess maybe route or file dir I didn't put to correct position, can u show me ur files with dirs and ur config info? or give me some direction guide?

**Comment by leejinzhu** [comment]
> I have the same situation with you, but I don't know which `Application.Php` I should edit for solve the issue. Maybe u mean to edit the `/vendor/caoym/phpboot/Application.php`, I saw this. But in my opinion, I think this just default config if not supply config.php with framework function `createByDefault`, I supplied another config file for sure. So I guess maybe route or file dir I didn't put to correct position, can u show me ur files with dirs and ur config info? or give me some direction guide?

Oh I See, use the right nginx root dir(your project path) or htaccess file can fix this. Also, change nginx default user from www-data to user current login user or root.
