### ISSUE TITLE
BasicAuth class unknown method fail

### ISSUE THREAD

**Issue by Kambaa** [caoym/phpboot-example#3]
At `Hooks/BasicAuth.php:28`  there's a `fail` method tries to run in the line but i couldn't find any definition. Could you help? 
```
        $auth[1] == md5("{$this->username}:{$this->password}") or fail(new UnauthorizedHttpException('Basic realm="PhpBoot Example", "Invalid username or password!"'));
```

Thank you.

**Comment by Kambaa** [comment]
thanks...

**Comment by caoym** [comment]
hi, i've just push some code to make the  BasicAuth work
the online demo is http://example.phpboot.org/users/myself
username: test
password:test
